name: ML-PROJECT
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - affine=2.4.0
  - anyio=4.11.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.12.12
  - cuda-version=12.9
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - freexl=2.0.0
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.13.0
  - geotiff=1.7.4
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=11.0.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.7.7
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.6
  - libcurl=8.17.0
  - libde265=1.0.15
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal-core=3.10.0
  - libglib=2.84.0
  - libgomp=15.2.0
  - libheif=1.18.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - libkml=1.3.0
  - liblapack=3.11.0
  - libpng=1.6.51
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxgboost=3.1.2
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - minizip=4.0.6
  - mistune=3.1.4
  - mkl=2025.3.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.6
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - numpy=2.3.5
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.6.0
  - osmnx=2.0.6
  - osmnx-base=2.0.6
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.44
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - proj=9.5.1
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - py-xgboost=3.1.2
  - pycparser=2.22
  - pygments=2.19.2
  - pyogrio=0.10.0
  - pyparsing=3.2.5
  - pyproj=3.7.1
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.12
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.0
  - rasterio=1.4.3
  - rav1e=0.7.1
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rio-vrt=0.3.1
  - rpds-py=0.29.0
  - scikit-learn=1.7.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shapely=2.0.7
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - snuggs=1.4.7
  - soupsieve=2.8
  - sqlite=3.51.0
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.5.0
  - tk=8.6.15
  - tomli=2.3.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - x265=3.5
  - xerces-c=3.2.5
  - xgboost=3.1.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - git-filter-repo==2.47.0
      - osmium==4.2.0
      - scipy==1.16.3
prefix: C:\Users\Laptop\anaconda3\envs\ML-PROJECT
